version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo Building Docker image...
      - docker build -t fitness-app .
      - docker tag fitness-app:latest $ECR_REPO/fitness-app:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_REPO/fitness-app:latest
      - echo Image pushed successfully.
