version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - docker build -t fitness-app .

      - docker tag fitness-app:latest $ECR_REPO/fitness-app:latest

  post_build:
    commands:
      - docker push $ECR_REPO/fitness-app:latest

      - aws ssm send-command \
        --instance-ids $INSTANCE_ID \
        --document-name "AWS-RunShellScript" \
        --parameters commands="cd /home/ubuntu/deploy && ./deploy.sh" \
        --region ap-southeast-2